MODEL:
  TYPE: swin_rope
  NAME: swin_rope_axial_base_patch4_window7_224
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
  SWIN_ROPE:
    THETA: 50
    MIXED: False
    RPB: False