MODEL:
  TYPE: swin_rope
  NAME: swin_rope_axial_small_patch4_window7_224
  DROP_PATH_RATE: 0.3
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
  SWIN_ROPE:
    THETA: 50
    MIXED: False
    RPB: False